06 roguelike
egor-bogomolov/software-design pull request #4
Opened 2018-05-29 01:33 UTC by egor-bogomolov

2018-06-02 18:13 UTC, yurii-litvinov requested changes
- Кажется, враги бьют дважды за ход, поэтому меня всё время убивают :)
- Нужны комментарии, логирование действий пользователя и хотя бы парочка юнит-тестов на функциональность по Вашему выбору.
Замечания по коду, в принципе, можно не править.

2018-06-02 18:13 UTC, yurii-litvinov commented on 06-roguelike/src/main/kotlin/controller/EnemyController.kt
> +class EnemyController(
Надо ещё комментарии

2018-06-02 18:13 UTC, yurii-litvinov commented on 06-roguelike/src/main/kotlin/controller/screens/GameScreenController.kt
> +                            state.getPlayer().addHp(1)
Регенерация --- наверное, важная часть игровой механики, не очень хорошо прятать её в контроллере пользовательского ввода

2018-06-02 18:13 UTC, yurii-litvinov commented on 06-roguelike/src/main/kotlin/controller/screens/GameScreenController.kt
> +                        }
Это тоже, некоторый копипаст с EnemyController-ом, может, можно было вынести в отдельный класс и использовать и отсюда, и оттуда

2018-06-03 11:51 UTC, egor-bogomolov commented
@yurii-litvinov 
Добавил тесты, логгирование и комментарии.
Враги не бьют дважды за ход, а бьют на своем ходу. Изменил их статы, теперь умереть можно только по неосторожности :)

2018-06-03 12:26 UTC, yurii-litvinov approved these changes
Хорошо, зачтена

2018-06-08 11:42 UTC, closed without merging